services:
  admin:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: admin_dev # Reference the specific build target
    ports:
      - "3333:3000"
    environment:
      PAYLOAD_SECRET: supersecret
      POSTGRES_URL: postgres://user:password@postgres:5432/mydb
    volumes:
      - type: bind
        # Use forward slashes and the /c/ drive mapping
        source: /c/Users/Jan/AppData/Local/pnpm/store
        target: /root/.local/share/pnpm
    command: sleep infinity # Keep the container running for development
    develop:
      watch:
        # Sync changes from the admin package
        - action: sync
          path: ./packages/admin
          target: /usr/src/app/packages/admin
          ignore:
            - node_modules
        # Sync changes from the shared package
        - action: sync
          path: ./packages/common
          target: /usr/src/app/packages/common
  website:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: website_dev # Reference the specific build target
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      PAYLOAD_SECRET: supersecret
      POSTGRES_URL: postgres://user:password@postgres:5432/mydb
    develop:
      watch:
        # Sync changes from the website package
        - action: sync
          path: ./packages/website
          target: /usr/src/app/packages/website
          ignore:
            - node_modules
        # Sync changes from the shared package
        - action: sync
          path: ./packages/common
          target: /usr/src/app/packages/common

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongodb:
    image: mongo:8.0 
    ports:
      - "27017:27017" # Map host port 27017 to container port 27017
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: jan
      MONGO_INITDB_ROOT_PASSWORD: jan
      MONGO_INITDB_ROOT_DATABASE: jan
    restart: unless-stopped # Restart the container unless it is stopped manually

  memgraph:
    image: memgraph/memgraph-mage:latest
    container_name: memgraph-mage
    ports:
      - "7687:7687"
      - "7444:7444"
    command: ["--log-level=TRACE"]
 
  lab:
    image: memgraph/lab:latest
    container_name: memgraph-lab
    ports:
      - "3000:3000"
    depends_on:
      - memgraph
    environment:
      - QUICK_CONNECT_MG_HOST=memgraph
      - QUICK_CONNECT_MG_PORT=7687
volumes:
  pgdata:
  mongodb-data:
